## Machine Learning
## Homework 1
## Mark Hovsepyan

## libraries (please install before running with install.packages())
library(ggplot2)
library(MASS)
library(ISLR)
library(GGally)


## Problem 8
data(Auto)
Auto$origin <- as.factor(Auto$origin)
## I made origin into factor so that its easier to distinguish

## a)
str(Auto)

## Quantitative variables - mpg, displacement, horsepower, weight, acceleration, cylinders, year
## Qualitative variables - name, origin
## year can be treated as both, but I decided to treat it as a quantitative

## b)
## let's subset quantitative variables
nums <- unlist(lapply(Auto, is.numeric))  
quant_auto <- Auto[, nums]

sapply(quant_auto, range)
## see the ranges generated by the above command


## c)
sapply(quant_auto, function(x) signif(c(mean(x), sd(x)), 3)) # used signif() to round
## first row is the means, second row is the standard deviations of quantitative predictors


## d)
cor(quant_auto)

## pairs() from standard plots
pairs(quant_auto, panel = panel.smooth, main = "Scatter Plots of Quantitative Pairs of Predictors")

## ggpairs() from GGally library (it uses ggplot2 as a base)
ggpairs(Auto[, 1:8], aes(fill = origin, alpha = 0.4))

## let's see how MPG is related to year
boxplot(Auto$mpg ~ Auto$year , xlab = "Year", ylab = "MPG", main = "Boxplots of mpg according to year")

## same using ggplot2
ggplot(Auto, aes(group = year, x = year, y = mpg)) + 
  geom_boxplot() +
  ggtitle("Boxplots of MPG According to Year")

## more plots with ggplot2
ggplot(Auto, aes(group = origin, x = origin, y = mpg)) + 
  geom_boxplot() +
  ggtitle("Boxplots of MPG According to Origin")

## acceleration and mpg relation
ggplot(Auto, aes(colour = year, shape = origin, x = acceleration, y = mpg)) + 
  geom_point() +
  ggtitle("Scatterplot of MPG and Acceleration")

## weight and horsepower relation
ggplot(Auto, aes(x = horsepower, y = weight)) + 
  geom_point() +
  ggtitle("Scatterplot of Weight and Horsepower")

## acceleration and horsepower relation
ggplot(Auto, aes(x = horsepower, y = acceleration)) + 
  geom_point() +
  ggtitle("Scatterplot of Acceleration and Horsepower")

## We can observe that there are several notable correlations.
## Weight of the car is positively affecting the horsepower, which seems logical in real life.
## Moreover, acceleration is in a negative correlation with horsepower, 
## the more horsepower the car has the less is its acceleration (its heavier as well, so makes sense)
## Many other important observations are made in the (e) part.


## e)
## As we can see on the plots above, there are some variables that will be important in that task.
## Variables such as year, acceleration, and origin would be decent predictors of mpg.
## year, acceleration, and origin are highly correlated as we see on the scatterplots and boxplots.
## Their changes affect the mpg drastically, so they would give us quite accurate estimates of mpg.
## For example. average mpg changes sharply from year to year depending on the origin.
## Moreover, acceleration is affected by mpg and vice versa, so knwoing ones gives as a rough estimate of the other.



## Problem 9
data(Boston)

## a)
str(Boston)

## Examining the structure of the dataset, we can see that there are 506 rows and 14 columns
## Every columns is a predictor variable
## For every predictor observations were made in 506 neighborhoods of Boston
## Each represents a set of predictor observations made in one of those 506 neighborhoods


## b)
pairs(Boston, panel = panel.smooth, main = "Scatter Plots of All Pairs of Predictors")
#?Boston

## Since all of the variables are either num or int, 
## we can straight away make a pairwise scatterplots using pairs() function of R.
## However, it is really hard to make useful comments even if we zoom to individual plots
## the most obvious finding is that some variables are correlated (some more some less),
## while others are not.
## For example, medv and lstat, medv and rm, nox and dis are among strongly correlated ones
## One interesing thing is that access to radial highways seems to affect the rate of crime, as
## rad - index of accessibility to radial highways contains the highest level of  cri - per capita crime rate by area

## c)
cor(Boston)

Boston.corr = cor(Boston)
Boston.corr.crim = Boston.corr[-1,1]
Boston.corr.crim[order(abs(Boston.corr.crim), decreasing = T)]

## As mentioned before acces to radial hoghways (rad) seems to cause higher crime rates.
## This can occur, since highways provide a convenient zone for criminals to act.
## The next one is property-tax rate per \$10.000 (tax) that has more than 0.5 correlation to crime rates.
## That one is a bit harder ti explain, but seeminlgy it has connection with the high value of property in the area.
## Thus, being attarctive for criminals.
## Other predictors are not highly correlated with crim and are not really significant.


## d)
## let's make some observations and use histograms
summary(Boston$crim)
qplot(Boston$crim, binwidth = 3 , xlab = "Crime rate", ylab = "# of Neighborhoods" )
## Yes, as the maximum value is much higher than the 3rd quartile, we can state that
## there are several areas with unusually high crime rates (can be seen on the plot)

summary(Boston$tax)
qplot(Boston$tax, binwidth = 20, xlab = "Property tax per $10,000", ylab = "# of Neighborhoods" )
## Yes, there are many areas with really high taxes. So, let's count those higher than 500.
length(Boston$tax[Boston$tax > 500])
## there are 137 areas, with particularly high tax rates.

summary(Boston$ptratio)
qplot(Boston$ptratio, binwidth = 1, xlab = "Pupil-teacher ratio", ylab = "# of Neighborhoods" )
## There is a concentration of high pupil-teacher ratios around 20 and over 150 suburbs are in that segment.
## However, 3rd quartile and max are pretty close to each other and to the mean, 
## so no there are particularly high ratios.

## e)
nrow(subset(Boston, chas == 1)) ## counting rows with chas value equal to 1
## there are 35 suburbs



